services:
  - type: web
    name: angular-app
    env: docker
    plan: free
    dockerImage: ghcr.io/harshadm92/angulardockerizedapp:latest
    autoDeploy: true  # Enables auto-deploy for the main branch